

<html>
    <head>
        
        <style>
            html { 
                background: url('/uploads/2.jpeg') no-repeat center center fixed; 
                -webkit-background-size: cover;
                -moz-background-size: cover;
                -o-background-size: cover;
                background-size: cover;
            }
            
            * {font-family: Helvetica Neue, Arial, sans-serif; }


		h1, table { text-align: center; }

		table {border-collapse: collapse;  width: 70%; margin: 0 auto 5rem;}

		th, td { padding: 1.5rem; font-size: 1.3rem; }

		tr {background: hsl(50, 50%, 80%); }

		tr, td { transition: .4s ease-in; } 

		tr:first-child {background: hsla(12, 100%, 40%, 0.5); }

		tr:nth-child(even) { background: hsla(50, 50%, 80%, 0.7); }

		td:empty {background: hsla(50, 25%, 60%, 0.7); }

		tr:hover:not(#firstrow), tr:hover td:empty {background: #ff0; pointer-events: visible;}
		tr:hover:not(#firstrow) { transform: scale(1.2); font-weight: 700; box-shadow: 0px 3px 7px rgba(0, 0, 0, 0.5);}

		
	    img{
		width: 85px;
		height:70px;
	    }
	    table{
		font-style: italic;
		color:#000080;
	    }
            fieldset{
                text-align: center;
                font-family: Comic Sans Ms;
                width: 400px;
                margin: 200px auto;
                font-size:24px;
                color:#009900;
                border-style:groove;
                opacity:.8;
               -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=80)";
                background-color:#DEB887;
           }
           .menuimg{
		width: 125px;
		height:7%;
		
		}
	    	@import url(http://fonts.googleapis.com/css?family=Lato:300,400,700);
		@charset "UTF-8";
		/* Base Styles */
		#cssmenu ul,
		#cssmenu li,
		#cssmenu a {
		  list-style: none;
		  margin: 0;
		  padding: 0;
		  border: 0;
		  line-height: 2;
		  font-family: 'Lato', sans-serif;
		}
		
		#cssmenu {
		  border: 2px solid #133e40;
		  -webkit-border-radius: 5px;
		  -moz-border-radius: 5px;
		  -ms-border-radius: 5px;
		  -o-border-radius: 5px;
		  border-radius: 5px;
		  width: auto;
		}
		#cssmenu ul {
		  zoom: 1;
		  background: #CD853F;
		  background: -moz-linear-gradient(top, #CD853F 0%, #CD853F 100%);
		  background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #36b0b6), color-stop(100%, #2a8a8f));
		  background: -webkit-linear-gradient(top, #36b0b6 0%, #2a8a8f 100%);
		  background: -o-linear-gradient(top, #36b0b6 0%, #2a8a8f 100%);
		  background: -ms-linear-gradient(top, #36b0b6 0%, #2a8a8f 100%);
		  background: linear-gradient(top, #36b0b6 0%, #2a8a8f 100%);
		  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='@top-color', endColorstr='@bottom-color', GradientType=0);
		  padding: 5px 10px;
		  -webkit-border-radius: 5px;
		  -moz-border-radius: 5px;
		  -ms-border-radius: 5px;
		  -o-border-radius: 5px;
		  border-radius: 5px;
		}
		#cssmenu ul:before {
		  content: '';
		  display: block;
		}
		#cssmenu ul:after {
		  content: '';
		  display: table;
		  clear: both;
		}
		#cssmenu li {
		  float: left;
		  margin: 0 5px 0 0;
		  border: 1px solid transparent;
		}
		#cssmenu li a {
		  -webkit-border-radius: 5px;
		  -moz-border-radius: 5px;
		  -ms-border-radius: 5px;
		  -o-border-radius: 5px;
		  border-radius: 5px;
		  padding: 8px 15px 9px 15px;
		  padding-top:10px;
		  display: block;
		  text-decoration: none;
		  color: #ffffff;
		  border: 1px solid transparent;
		  font-size: 24px;
		}
		
		#cssmenu li:hover {
		  -webkit-border-radius: 5px;
		  -moz-border-radius: 5px;
		  -ms-border-radius: 5px;
		  -o-border-radius: 5px;
		  border-radius: 5px;
		  border: 1px solid #36b0b6;
		}
		#cssmenu li:hover a {
		  -webkit-border-radius: 5px;
		  -moz-border-radius: 5px;
		  -ms-border-radius: 5px;
		  -o-border-radius: 5px;
		  border-radius: 5px;
		  display: block;
		  background: #D2B48C;
		  border: 1px solid #133e40;
		  -moz-box-shadow: inset 0 5px 10px #133e40;
		  -webkit-box-shadow: inset 0 5px 10px #133e40;
		  box-shadow: inset 0 5px 10px #133e40;
		}

            

        </style>


    </head>
<?php  
    $authorization =Zend_Auth::getInstance();
    $info = $authorization->getIdentity();
    if(!empty($info)){
        $admin=$info->admin;
        $userName=$info->userName;
        $userImage=$info->userImage;
    }
    

?>
    <div id='cssmenu'>
        <ul><li><a href='<?php echo $this->baseUrl();?>/fourm/list'><span>Home</span></a></li>
            <li><a href='<?php echo $this->baseUrl();?>/user/profile'><span>Profile</span></a></li>
            <li><a href='<?php echo $this->baseUrl();?>/user/messageusersend'><span>message, you send it!</span></a></li> 
            <li><a href='<?php echo $this->baseUrl();?>/user/showmessage'><span>message, you recieved it!</span></a></li>
             
                
<?php
if(!empty($info)){
    if($admin==1){
            echo "";
            echo "<li><a href='".$this->baseUrl()."/user/list'><span>list User</span></a></li>

                  <li><a href='".$this->baseUrl()."/user/site'><span>open or close Site</span></a></li>
                  <li><a href='".$this->baseUrl()."/user/add'><span>Add User</span></a></li>";
            //echo 'admin';        exit();

     }else{
            //echo 'normal user';        exit();
     }
}

$url= $_SERVER['REQUEST_URI'];
if($url!=$this->baseUrl().'/user/login'){
?>
<li><a href="<?php echo $this->baseUrl()?>/user/logout">Logout</a></li>
<li style='float:right;'><a href='<?php echo $this->baseUrl();?>/user/profile'><span>&nbsp;<?php echo $userName;?></span></a></li>
        <div style='float:right;' ><a href='<?php echo $this->baseUrl();?>/user/profile' title='Return to the homepage' id='logo'>
		  	<img class='menuimg' src='<?php echo $this->baseUrl()?>/uploads/<?php echo $userImage; ?>' alt='Nike logo' /></a></div></ul>
<?php
}
?>
    </div>
<?php echo $this->layout()->content;?>
    
</html>