
    <head>
        
        <style>
           /* html { 
                background: url('/uploads/2.jpeg') no-repeat center center fixed; 
                -webkit-background-size: cover;
                -moz-background-size: cover;
                -o-background-size: cover;
                background-size: cover;
            }*/
        </style>
    </head>
<br /><br />
<div id="view-content">
	<!--p>View script for controller <b>user</b> and script/action name <b>login</b></p-->
</div>
<fieldset>
<?php
echo $this->form;
?>
</fieldset>
