<br /><br />
<div id="view-content">
	<p>View script for controller <b>post</b> and script/action name <b>userpost</b></p>
</div>
<table>
     <tr>
        <?php
            for($i = 0; $i<1; $i++){
                foreach ($this->post[$i] as $key=>$value):
                    if($key=='postName'){
                        echo "<td>".$key."</td>";
                    }
                endforeach;
            }
        ?>
        <td> action </td>    
    </tr>   
</table>